export const products = [
  {
    id: 1,
    name: "Refrigerator",
    stock: 5,
    price: 600,
    image: "/fridge.jpeg",
    category: "kitchen appliances",
  },
  {
    id: 2,
    name: "Grill Set",
    stock: 8,
    price: 150,
    image: "/grill.jpeg",
    category: "Electronic",
  },
  {
    id: 3,
    name: "Cheese Grater",
    stock: 10,
    price: 10,
    image: "/grater.jpeg",
    category: "Kitchen appliances",
  },
  {
    id: 4,
    name: "Chef's Knife",
    stock: 7,
    price: 30,
    image: "/knife.jpeg",
    category: "Kitchen appliances",
  },
  {
    id: 5,
    name: "Coffee Machine",
    stock: 3,
    price: 300,
    image: "/machine.jpeg",
    category: "Electronic",
  },
  {
    id: 6,
    name: "Office Chair",
    stock: 6,
    price: 50,
    image: "/chair.jpeg",
    category: "Furniture",
  },
  {
    id: 7,
    name: "Lounge Chair",
    stock: 4,
    price: 40,
    image: "/chair2.jpeg",
    category: "Furniture",
  },
  {
    id: 8,
    name: "Dining Chair",
    stock: 2,
    price: 35,
    image: "/chair3.jpeg",
    category: "Furniture",
  },
  {
    id: 9,
    name: "Comfortable Sofa",
    stock: 9,
    price: 200,
    image: "/sofa.jpeg",
    category: "Furniture",
  },
  {
    id: 10,
    name: "Modern Sofa",
    stock: 1,
    price: 180,
    image: "/sofa2.jpeg",
    category: "Furniture",
  },
  {
    id: 11,
    name: "Leather Sofa",
    stock: 6,
    price: 220,
    image: "/sofa3.jpeg",
    category: "Furniture",
  },
  {
    id: 12,
    name: "Drone with Camera",
    stock: 3,
    price: 500,
    image: "/drone.jpeg",
    category: "Electronic",
  },
  {
    id: 13,
    name: "Professional Drone",
    stock: 5,
    price: 450,
    image: "/drone2.jpeg",
    category: "Electronic",
  },
  {
    id: 14,
    name: "Digital Camera",
    stock: 7,
    price: 350,
    image: "/camera.jpeg",
    category: "Electronic",
  },
  {
    id: 15,
    name: "Mirrorless Camera",
    stock: 2,
    price: 400,
    image: "/camera2.jpeg",
    category: "Electronic",
  },
  {
    id: 16,
    name: "Samsung s21 Ultra",
    stock: 10,
    price: 600,
    image: "/samsung.jpeg",
    category: "Electronic",
  },
  {
    id: 17,
    name: "Striped Shirt",
    stock: 20,
    price: 25,
    image: "/shirt2.jpeg",
    category: "Clothing",
  },
  {
    id: 18,
    name: "Formal Shirt",
    stock: 12,
    price: 18,
    image: "/shirt3.jpeg",
    category: "Clothing",
  },
  {
    id: 19,
    name: "Travel Backpack 3",
    stock: 10,
    price: 50,
    image: "/bag3.jpeg",
    category: "Groceries & food",
  },
  {
    id: 20,
    name: "Business Suit",
    stock: 8,
    price: 120,
    image: "/suit.jpeg",
    category: "Clothing",
  },
  {
    id: 21,
    name: "Designer Suit",
    stock: 10,
    price: 150,
    image: "/suit2.jpeg",
    category: "Clothing",
  },
  {
    id: 22,
    name: "Running Shoes",
    stock: 25,
    price: 80,
    image: "/shoes.jpeg",
    category: "Clothing",
  },
  {
    id: 23,
    name: "Bricks",
    stock: 21,
    price: 4,
    image: "/cons1.jpeg",
    category: "Construction",
  },
  {
    id: 24,
    name: "Google Pixel 7",
    stock: 8,
    price: 250,
    image: "/pixel1.jpeg",
    category: "Electronic",
  },
  {
    id: 25,
    name: "construction steel",
    stock: 60,
    price: 32,
    image: "/cons3.jpeg",
    category: "Construction",
  },
  {
    id: 26,
    name: "Athletic Shoes",
    stock: 18,
    price: 100,
    image: "/shoes2.jpeg",
    category: "Clothing",
  },
  {
    id: 27,
    name: "Trouser",
    stock: 2,
    price: 44,
    image: "/trouser.jpeg",
    category: "Clothing",
  },
  {
    id: 28,
    name: "T-shirt",
    stock: 5,
    price: 25,
    image: "/tshirt.jpeg",
    category: "Clothing",
  },
  {
    id: 29,
    name: "Jeans",
    stock: 8,
    price: 35,
    image: "/jeans.jpeg",
    category: "Clothing",
  },
  {
    id: 30,
    name: "Sweater",
    stock: 4,
    price: 40,
    image: "/sweater.jpeg",
    category: "Clothing",
  },
  {
    id: 31,
    name: "Sneakers",
    stock: 6,
    price: 55,
    image: "/sneakers.jpeg",
    category: "Clothing",
  },
  {
    id: 32,
    name: "Backpack",
    stock: 10,
    price: 30,
    image: "/bag.jpeg",
    category: "Groceries & food",
  },
  {
    id: 33,
    name: "Cements",
    stock: 11,
    price: 20,
    image: "/cons2.jpeg",
    category: "Construction",
  },
  {
    id: 34,
    name: "Watch",
    stock: 7,
    price: 75,
    image: "/watch.jpeg",
    category: "Jewelry",
  },
  {
    id: 35,
    name: "MacBook Air M1",
    stock: 7,
    price: 1200,
    image: "/m1.jpeg",
    category: "Electronic",
  },
  {
    id: 36,
    name: "Gloves",
    stock: 9,
    price: 15,
    image: "/gloves.jpeg",
    category: "Construction",
  },
  {
    id: 37,
    name: "Oracle Box 2",
    stock: 10,
    price: 300,
    image: "/vr.jpeg",
    category: "Games",
  },
  {
    id: 38,
    name: "PlayStation 4",
    stock: 15,
    price: 400,
    image: "/ps4.jpeg",
    category: "Games",
  },
  {
    id: 39,
    name: "Casual Shirt",
    stock: 15,
    price: 20,
    image: "/shirt.jpeg",
    category: "Clothing",
  },
  {
    id: 40,
    name: "Bicycle",
    stock: 12,
    price: 150,
    image: "/cycle.jpeg",
    category: "Sports",
  },
  {
    id: 41,
    name: "Lorex watch",
    stock: 18,
    price: 300,
    image: "/watch2.jpeg",
    category: "Jewelry",
  },
  {
    id: 42,
    name: "PlayStation 5",
    stock: 8,
    price: 500,
    image: "/ps5.jpeg",
    category: "Games",
  },
  {
    id: 43,
    name: "MacBook Pro 2019",
    stock: 5,
    price: 1200,
    image: "/macbook.jpeg",
    category: "Electronic",
  },
  {
    id: 44,
    name: "Dress",
    stock: 3,
    price: 60,
    image: "/dress.jpeg",
    category: "Clothing",
  },
  {
    id: 45,
    name: "Travel Backpack",
    stock: 25,
    price: 40,
    image: "/bag4.jpeg",
    category: "Groceries & food",
  },
  {
    id: 46,
    name: "Marriage Ring",
    stock: 3,
    price: 200,
    image: "/ring.jpeg",
    category: "Jewelry",
  },
  {
    id: 47,
    name: "iPhone 12 promax",
    stock: 7,
    price: 800,
    image: "/iphone2.jpeg",
    category: "Electronic",
  },
  {
    id: 48,
    name: "Gas Stove",
    stock: 6,
    price: 180,
    image: "/gas.jpeg",
    category: "Kitchen appliances",
  },
  {
    id: 49,
    name: "Bicycle ",
    stock: 10,
    price: 200,
    image: "/cycle2.jpeg",
    category: "Sports",
  },
  {
    id: 50,
    name: "Meta 3",
    stock: 15,
    price: 350,
    image: "/vr2.jpeg",
    category: "Games",
  },
  {
    id: 51,
    name: "Cosmetics",
    stock: 30,
    price: 25,
    image: "/cosmetics.jpeg",
    category: "Health & Beauty",
  },
  {
    id: 52,
    name: "iPhone 12 Mini",
    stock: 12,
    price: 700,
    image: "/iphone.jpeg",
    category: "Electronic",
  },
  {
    id: 53,
    name: "Cosmetics 2",
    stock: 20,
    price: 30,
    image: "/cosmetics2.jpeg",
    category: "Health & Beauty",
  },
  {
    id: 54,
    name: "Pixel 7 pro",
    stock: 15,
    price: 300,
    image: "/pixel2.jpeg",
    category: "Electronic",
  },
  {
    id: 55,
    name: "Gas Stove ",
    stock: 5,
    price: 200,
    image: "/gas2.jpeg",
    category: "Kitchen appliances",
  },
  {
    id: 56,
    name: "Catepilary",
    stock: 2,
    price: 500,
    image: "/truck.jpeg",
    category: "Construction",
  },
  {
    id: 57,
    name: "Groceries",
    stock: 20,
    price: 50,
    image: "/groceries2.jpeg",
    category: "Groceries & food",
  },
  {
    id: 58,
    name: "Hat",
    stock: 1,
    price: 20,
    image: "/hat.jpeg",
    category: "Clothing",
  },
  {
    id: 59,
    name: "Freddy",
    stock: 3,
    price: 20,
    image: "/feed2.jpeg",
    category: "Clothing",
  },
  {
    id: 60,
    name: "Freddy",
    stock: 3,
    price: 25,
    image: "/feed2.jpeg",
    category: "Clothing",
  },
];
